---
  dataSource: "issues"
  prefix: ""
  ignoreIssuesWith: 
    - "duplicate"
    - "invalid"
  onlyMilestones: false
  ignoreTagsWith: 
    - "init-container"
    - "cli"
    - "encryptor"
    - "decryptor"
  groupBy: 
    - Enhancements: ["enhancement", "documentation"]
    - Bug Fixes: ["bug"]

  changelogFilename: "CHANGELOG.md"
