{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "kamus.name" . -}}
{{- $servicePort := .Values.service.externalPort -}}
{{- $servicePath := .Values.ingress.path | default "/" -}}
{{- $tlsSecretName := .Values.ingress.tls.secretName -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "kamus.name" . }}
  namespace: {{ .Values.team }}
  labels:
    app: {{ template "kamus.name" . }}
    component: encryptor
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $servicePath }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end }}

  tls:
    - hosts:
    {{- range $host := .Values.ingress.hosts }}
      - {{ $host }}
    {{- end }}

      secretName: {{ $tlsSecretName }}
{{- end -}}