apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.team }}
  name: {{ include "kamus.name" . }}
type: Opaque
data:
  appsettings.secret.json: {{ include "appsettings.secret.json"  . | b64enc}}