apiVersion: v1
kind: Service
metadata:
  name: {{ template "kamus.name" . }}-encryptor
  namespace: {{ .Values.team }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "kamus.name" . }}
    component: encryptor
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      {{- if .Values.useAirbag }}
      targetPort: {{ .Values.airbag.airbagPort }} 
      {{- else }} 
      targetPort: 9999
      {{- end }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "kamus.name" . }}
    component: encryptor
    release: {{ .Release.Name }}
