@startuml

actor User 
participant EncryptApi
participant KMS
participant DecryptApi
participant Pod
participant KubernetesApi

== Encryption ==

autonumber
User -> EncryptApi: Encrypt - data, namespace, service account
EncryptApi -> KMS: Encrypt - data, namespace, service account
KMS ->  EncryptApi: Enrypted data
EncryptApi -> User: Enrypted data

== Decryption ==
autonumber 1
Pod -> DecryptApi: Decrypt - data, service account token
DecryptApi -> KubernetesApi: TokenReview - token
KubernetesApi -> DecryptApi: service account, namespace
DecryptApi -> KMS: Decrypt - data, service account, namespace
KMS -> DecryptApi: Decrypted data
DecryptApi -> Pod: Decrypted data

@enduml