@startuml

actor User 
participant Pod
participant Kamus
participant KubernetesApi
participant KMS

== Encryption ==

autonumber
User -> Kamus: Encrypt - data, namespace, service account
Kamus -> KubernetesApi: Get Service Account - namespace, service account
KubernetesApi -> Kamus: Service Account details
Kamus -> Kms: Encrypt - data, namespace, service account
Kms -> Kamus: Enrypted data
Kamus -> User: Enrypted data

== Decryption ==
autonumber 1
Pod -> Kamus: Decrypt - data, service account token
Kamus -> KubernetesApi: TokenReview - token
KubernetesApi -> Kamus: service account, namespace
KamusApi -> Kms: Decrypt - data, service account, namespace
Kms -> Kamus: Decrypted data
Kamus -> Pod: Decrypted data

@enduml