apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: kamussecrets.soluto.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: soluto.com
  # version name to use for REST API: /apis/<group>/<version>
  version: v1alpha1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: kamussecrets
    # singular name to be used as an alias on the CLI and for display
    singular: kamussecret
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: KamusSecret
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
     - ks